DROP DATABASE IF EXISTS CAFE;
CREATE DATABASE CAFE;
USE CAFE;

DROP TABLE IF EXISTS EMPLOYEE;
CREATE TABLE EMPLOYEE
(
  employeeID INT AUTO_INCREMENT,
  name TEXT,
  position TEXT,
  salary FLOAT,
  PRIMARY KEY (employeeID)
);
ALTER TABLE EMPLOYEE AUTO_INCREMENT = 101;

DROP TABLE IF EXISTS SUPPLIER;
CREATE TABLE SUPPLIER
(
  name TEXT,
  type TEXT,
  cost FLOAT,
  stock INT,
  PRIMARY KEY (name, type),
);

DROP TABLE IF EXISTS COFFEESELECTION;
CREATE TABLE COFFEESELECTION
(
  drink TEXT,
  size TEXT,
  type TEXT,
  roast TEXT,
  price FLOAT,
  stock INT,
  PRIMARY KEY (drink, size),
  FOREIGN KEY (type) REFERENCES SUPPLIER (type)
  ON UPDATE CASCADE
  ON DELETE SET NULL
);

DROP TABLE IF EXISTS CUSTOMER;
CREATE TABLE CUSTOMER
(
  name TEXT,
  favoriteDrink TEXT,
  size TEXT,
  PRIMARY KEY (name),
  FOREIGN KEY (favoriteDrink) REFERENCES COFFEESELECTION (drink),
  FOREIGN KEY (size) REFERENCES COFFEESELECTION (size)
);

DROP TABLE IF EXISTS TRANSACTION;
CREATE TABLE TRANSACTION
(
  transactionID INT,
  employeeID INT,
  customerName TEXT,
  drink TEXT,
  price FLOAT,
  updatedAt TIMESTAMP
  PRIMARY KEY (transactionID),
  FOREIGN KEY (employeeID) REFERENCES EMPLOYEE (employeeID)
  ON UPDATE CASCADE
  ON DELETE SET NULL,
  FOREIGN KEY (customerName) REFERENCES CUSTOMER (customerName)
  ON UPDATE CASCADE
  ON DELETE SET NULL,
  FOREIGN KEY (drink) REFERENCES COFFEESELECTION (drink)
  ON UPDATE CASCADE
  ON DELETE SET NULL,
  FOREIGN KEY (price) REFERENCES COFFEESELECTION (price)
  ON UPDATE CASCADE
  ON DELETE SET NULL,
);
